---
title: "hw2"
author: "Simon Lee"
date: "2022-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include= FALSE}
{
  library(ggplot2)
  library(tidyverse)
  library(tidymodels)
  library(corrplot)
  library(ggthemes)
  library(ISLR)
  tidymodels_prefer()
  getwd()
  abaloneD <- read.csv(file= "data/abalone.csv")
}
```

```{r}
abaloneD <- abaloneD %>% 
  mutate(age = rings+1.5) %>% 
  select(age, everything())

abaloneD %>% 
  ggplot(aes(x = age)) +
  geom_histogram(bins = 25)
```

From the histogram the age of the abalones has a slight right skew and the mass
of its distribution is centered around 5 and 15 years

```{r}
set.seed(115)
abalone_split <- initial_split(abaloneD, prop = 0.8, strata = age)
abalone_train <- training(abalone_split)
abalone_test <- testing(abalone_split)
```

```{r}
abalone_recipe <- recipe(age ~ type + longest_shell + diameter + height + whole_weight + shucked_weight + viscera_weight + shell_weight, data = abalone_train) %>% 
  step_dummy(all_nominal_predictors()) %>%
  step_interact(~ shucked_weight:shell_weight) %>% 
  step_interact(~ longest_shell:diameter) %>% 
  step_interact(terms= ~ starts_with("type"):shucked_weight) %>% 
  step_scale(all_predictors()) %>% 
  step_center(all_predictors())
abalone_recipe
```

There is no point trying to precit age using the rings variable since to count the rings
we would have to cut the shell open and count using a microscope. The model is made
to see if we can predict the age without the rings variable. 

```{r}
lm_model <- linear_reg() %>% 
  set_engine("lm")
```

```{r}
lm_wflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(abalone_recipe)
```

```{r}
lm_fit <- fit(lm_wflow, abalone_train)
pred_abalone <- predict(lm_fit, data.frame(type = 'F', longest_shell = 0.5, diameter = 0.1,
                                           height = 0.3, whole_weight = 4, shucked_weight = 1,
                                           viscera_weight = 2, shell_weight = 1))
pred_abalone
```

```{r}
library(yardstick)
abalone_metric <- metric_set(rmse, rsq, mae)
abalone_train_res <- predict(lm_fit, new_data = abalone_train %>% select(-age, -rings))
abalone_train_res %>% head()
abalone_train_res <- bind_cols(abalone_train_res, abalone_train %>% select(age))
abalone_train_res %>% head()
rmse(abalone_train_res, truth= age, estimate = .pred)
abalone_metric <- metric_set(rmse, rsq, mae)
abalone_metric(abalone_train_res, truth = age, estimate = .pred)
```

